---
title: "5b. GLS rarefaction"
output: html_document
date: "2026-04-21"
author: "Stylianos Koutalis"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# We perform the GLS rarefaction analysis with the phylogenetic covariance matrix, so as to verfy that the observed results of the phylogenetic regression are not hampered by the small sample size.


```{r message = FALSE}
library(RRPP)
library(stats)
library(ape)

rare<-rarefymenow(data=gdf.extant, n_rare = 7, n_reps = 1000, n_null = 20, tree = tree.all)
sum(rare$p_value<=0.05)

rarefymenow<-function(data, n_rare, n_reps, n_null, tree){
  start_time<-Sys.time()
  
  coords <-data$coords
  size<-data$size
  genera<-data$genera
  species<-data$species
  
  inds_macaca<-which(genera=="Macaques")
  inds_papio<-which(genera=="Papionins")
  p_value<-numeric(n_reps)
  Z<-numeric(n_reps)
  
  p_value_null<-matrix(NA, nrow=n_reps, ncol=n_null)
  Z_null<-matrix(NA, nrow=n_reps, ncol=n_null)
  
  for (i in seq_len(n_reps)) {
    samp_macaca<-sample(inds_macaca, n_rare)
    samp_papio<-inds_papio
    inds_use<-c(samp_macaca, samp_papio)
    
    coords_sub<-coords[, , inds_use]
    size_sub<-size[inds_use]
    genera_sub<-factor(data$genera[inds_use])
    species_sub<-species[inds_use]
    tree_sub<- ape::keep.tip(tree.all, as.character(species_sub))
   
 # Rarefy
fit_unique<-lm.rrpp.ws(coords~size*genera_sub, Cov=vcv(tree_sub), subjects="species_sub", data=rrpp.data.frame(coords= two.d.array(coords_sub), size=size_sub, genera_sub=genera_sub, species_sub=species_sub), SS.type="III")    
    dd<-anova(fit_unique)
    p_value[i]<-dd$table$`Pr(>F)`[3]
    Z[i]<-dd$table$Z[3]
    
    
    # Null Rarefy
    for (j in seq_len(n_null)) {
      genera_sub_null<-sample(genera_sub)
 
fit_unique_null<-lm.rrpp.ws(coords~size*genera_sub_null, Cov=vcv(tree_sub), subjects="species_sub", data=rrpp.data.frame(coords= two.d.array(coords_sub), size=size_sub, genera_sub_null=genera_sub_null, species_sub=species_sub), SS.type="III")    
      
      dd<-anova(fit_unique_null)
      p_value_null[i,j]<-dd$table$`Pr(>F)`[3]
      Z_null[i,j]<-dd$table$Z[3]
    }
    current_time<-Sys.time()
    elapsed<-as.numeric(current_time-start_time, units="secs")
    cat(sprintf("Iteration %d-Cumulative seconds elapsed: %.2f\n", i, elapsed))
  }
  return(list(p_value=p_value, Z=Z,
              p_value_null=p_value_null, Z_nul=Z_null))
}


rare<-rarefymenow(data=gdf.extant, n_rare = 7, n_reps = 1000, n_null = 20, tree = tree.all)

```

