---
title: "6. Shape prediction on same size – the effect of genus on landmarks"
output: html_document
date: "2026-04-21"
author: "Stylianos Koutalis"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# This is the scipt of the Least Square mean shape predictions, with the size covariate kept constant at the comparative sample mean value. This is ought to assist in the discrimination of genus level differences among specimens.


```{r message = FALSE}
# Create the data frame
load("Regscores.rda") # this loads the preexisting "gdf" dataframe that contains the coords (coordinates), size, geenera and species attributions of the complete dataset.

library(RRPP)
library(geomorph)
library(stas)

load("Regscores.rda")
cc<-two.d.array(gdf$coords)
ss<-as.vector(gdf$size)
row.names(cc)<-1:nrow(cc)
gg<-as.factor(gdf$genera)

sppp<-c(rep("M. arctoides",2), "M. assamensis", "M. cyclopis", rep("M. fascicularis",4), rep("M. nemestrina",6),
        rep("M. radiata",2), "M. nemestrina", rep("M. sinica",2), rep("M. sylvanus", 6), rep("M. thibetana", 2),
        rep("P. anubis", 4), "P. hamadryas", rep("P. papio",2),"Paradolichopithecus Schlager", "Paradolichopithecus Amano with", 
        "Paradolichopithecus Amano without", "Paradolichopithecus Schlager", "Paradolichopithecus Amano with", 
        "Paradolichopithecus Amano without","Paradolichopithecus Schlager", "Paradolichopithecus Amano with", 
        "Paradolichopithecus Amano without")

gdf1<-rrpp.data.frame(co=cc, size=ss, gen=gg, sub=sppp)

rm(list=ls()[! ls() %in% c("gdf1")])

#test the LS means statistic differences
fit <- lm.rrpp.ws(co ~  size + gen, subjects = "sub", data = gdf1, print.progress = FALSE, logsz=F, RRPP = T, iter = 10000,SS.type = "II") 
pw<-pairwise(fit, groups = gdf1$gen)
summary(pw, test.type = "dist", show.vectors=F)



# Predictions (holding alternative effects constant: this means, that, the Csize is held the same (the mean size of the comparative dataset),
  #. Not including the size in the "new data" and adding only genera, is like asking: if all genera had the same size,
  # would there be separation based on their genera differences???)
  shapeDF <- expand.grid(size=mean(gdf1$size[1:34]), gen = levels(gdf1$gen)) # size of the comparative material only
  rownames(shapeDF) <- paste0(shapeDF$gen)
  shapeDF
  
  mean(gdf1$size)
  shapePreds99 <- predict(fit, shapeDF, confidence = 0.95)
  #summary(shapePreds99, PC = TRUE)
  
  # Plot prediction PCA (not ggplot)
  rr<-plot(shapePreds99, PC = TRUE, ellipse = TRUE)
  plot(shapePreds99, PC = TRUE)

```
